---
title: "Lancet-SIGHT Commission Metrics WG: Large-N analyses"
author: "[Oskar Timo Thoms](mailto:timo.thoms@carleton.ca), Dane Rowlands, and [Valerie Percival](mailto:Valerie.Percival@carleton.ca)"
output:
  html_document:
    code_folding: NULL
---

## Research questions

In the large-N quantitative analyses, we examine the hypotheses of virtuous and vicious cycles. This is inspired by Suri et al's (2011) analysis of the relationship and feedback loops between human development and economic growth. In our context, the hypothesis is that health, gender, and violence variables interact with each other (and with their broader political and economic context) to produce reinforcing cycles, which can be both positive or negative. From the Lancet Commission's perspective, we are particularly interested in the direction of statistical effects from health and gender outcomes to violence, but also whether violence makes improvements in gender equality and health outcomes less likely. The key questions are:

* While accounting for the overall improvements that most countries have experienced in health and gender outcomes in recent decades, do those countries that score low in earlier periods improve less than the global average and/or high performers, or do they even decline?

* While accounting for possible ceiling effects, do those countries that score high in earlier periods a) maintain stable and high levels and b) avoid violence?

* Do countries that experience higher levels of violence a) improve less on gender equality and health outcomes than those with less violence, or b) do their gender and health outcomes even deteriorate?

* Are countries that score low on health and gender outcomes more prone to violence than those that score higher?

Since we're analyzing the data statistically, we are testing these questions in probabilistic terms, not in a deterministic fashion. Of course, there are many other factors influencing health, gender and violence outcomes. We do not aim to develop full causal models of each outcome, but to examine whether there are associations between the three categories of outcomes that are consistent with the virtuous and vicious cycles hypotheses.

## Our work to date

We have taken the following steps for far:

1. Identification of key gender, health and violence indicators as candidates for the analyses.

2. Assembly of a comprehensive dataset with the best available cross-national health, gender and violence indicators and other relevant variables (such as GDP per capita, political regime type, etc). This was presented at the Commission meeting in late June.

3. Analysis of the quality and availability of the available indicators.

4. Quantitative checks to identify representative measures from within each category (within-category correlations).

5. Across-category correlations to check basic bivariate statistical relationships between categories.

6. Classification of countries based on health and gender outcomes, in order to create groups of countries for comparison, to be used in examining the virtuous and vicious cycles hypotheses.

7. Bivariate graphical analyses of key measures to show health, gender, and violence trends within the classifications over time. Are there trajectories associated with certain classifications? Do these provide support for virtuous and vicious cycles?

8. Multivariate cross-sectional statistical models to test the hypotheses, and to explore intervening economic and political variables.

9. Multivariate panel models to further test the hypotheses and analytically separate virtuous and vicious cycles.

This work is shown on this website. We are currently extending these analyses to further our understanding of virtuous and vicious cycles, and explore nuances in the statistical relationships. We are also exploring sequences of change in gender and health outcomes to examine possible pathways from vicious to virtuous cycles. This ongoing work will be added to this site. 

## Other possible extensions

* Build fuller statistical models of individual outcomes in order to account for the role of other important factors.

* Examine the statistical effects of policy levers, such as foreign aid focused on health development. 

* Identify high and low achievers on the gender and health dimensions (while accounting for economic wealth) to further explore the role of violence and conflict and possible mediating factors in particular country cases, for instance the quality of government.

* Possible follow-up covid-19 extension of the above analyses: Do the cross-national classifications tell us anything useful about covid-19 outcomes?

<!-- * Determine effective graphical presentation of results. For instance, we may be able to use 3-D visualizations to show statistical associations between gender, health and violence at particular points in time. -->
