---
title: "Cross-sectional Regressions"
params: 
  optimize: true
---

```{r setup, include = FALSE}
source("_R/setup.R")
```

```{r startup}
IsTrue <- function(x) { !is.na(x) & x }
load("_data/LSCMWG_working_class.RData", verbose = TRUE)
df <- new
```

```{r model function}
RunModel <- function(equation, data = df) {
  fit <- eval(bquote(lm(.(equation), data = data)))
  print(list(
    classical = summary(fit), ## classical SEs
    robust = lmtest::coeftest(fit, vcov = sandwich::vcovHC(fit, type = "HC1")) ## CRSEs;  Stata robust default
    # can also use: coeftest(fit, vcov = vcovCL, cluster = ~ country)
  ))
  invisible(fit)
}
```

## Life expectancy regressions 

```{r life}
## Column 1:
fit <- RunModel(life_exp_wpp_growth1995_2015 ~ life_exp_wpp_1995 + imr_wpp_1995 + asfr_adol_wpp_1995 + conflict_internal_cumulative1989_1995 + deaths_civilians_int_rate_cumulative1996_2015 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1996_2015)
df$samplelife <- ifelse(df$country %in% 
                        na.omit(get_all_vars(fit$call$formula, data = df, country = country))[, "country"], 1, 0)
# auxilliary checks
# RunModel(life_exp_wpp_growth1995_2015 ~ life_exp_wpp_1995 + imr_wpp_1995 + asfr_adol_wpp_1995 + deaths_civilians_osv_rate_1995 + deaths_civilians_int_rate_cumulative1996_2015 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1996_2015)

## Column 2: (no lag DV)
RunModel(life_exp_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + conflict_internal_cumulative1989_1995 + deaths_civilians_int_rate_cumulative1996_2015 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1991_1995)
# auxilliary checks
# RunModel(life_exp_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + deaths_civilians_osv_rate_1995 + deaths_civilians_int_rate_cumulative1996_2015 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1991_1995)
# RunModel(life_exp_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + deaths_civilians_int_rate_1995 + deaths_civilians_int_rate_cumulative1996_2015 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1991_1995)
# RunModel(life_exp_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + conflict_internal_cumulative1989_1995 + deaths_civilians_osv_rate_cumulative1996_2015 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1991_1995)
# RunModel(life_exp_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + deaths_civilians_osv_rate_1995 + deaths_civilians_osv_rate_cumulative1996_2015 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1991_1995)
# RunModel(life_exp_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + deaths_civilians_int_rate_1995 + deaths_civilians_osv_rate_cumulative1996_2015 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1991_1995)
# RunModel(life_exp_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + conflict_internal_cumulative1989_1995 + conflict_internal_cumulative1996_2015 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1991_1995)
# RunModel(life_exp_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + deaths_civilians_osv_rate_1995 + conflict_internal_cumulative1996_2015 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1991_1995)
# RunModel(life_exp_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + deaths_civilians_int_rate_1995 + conflict_internal_cumulative1996_2015 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1991_1995)

## Column 3:(prediction)
RunModel(life_exp_wpp_growth1995_2015 ~ life_exp_wpp_1995 + imr_wpp_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1991_1995 + deaths_civilians_osv_rate_1995)
# auxilliary checks
# RunModel(life_exp_wpp_growth1995_2015 ~ life_exp_wpp_1995 + imr_wpp_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1991_1995 + deaths_civilians_int_rate_1995)
# RunModel(life_exp_wpp_growth1995_2015 ~ life_exp_wpp_1995 + imr_wpp_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1991_1995 + conflict_internal_cumulative1989_1995)

## Column 4: performance version
RunModel(perf_life_exp_wpp_growth1995_2015 ~ perf_imr_wpp_1995 + perf_asfr_adol_wpp_1995 + conflict_internal_cumulative1989_1995 + pc_rgdpe_avg_1995 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1991_1995)
# auxilliary checks
# RunModel(perf_life_exp_wpp_growth1995_2015 ~ perf_imr_wpp_1995 + perf_asfr_adol_wpp_1995 + deaths_civilians_osv_rate_1995 + pc_rgdpe_avg_1995 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1991_1995)

## no health variables (not reported)
RunModel(life_exp_wpp_growth1995_2015 ~ mys_ratio_hdr_1995 + deaths_civilians_int_rate_cumulative1996_2015)
cor(df[df$samplelife == 1, c("life_exp_wpp_1995", "imr_wpp_1995")])
cor(df[df$samplelife == 1, c("v2x_polyarchy_cumulative1996_2015", "v2x_polyarchy_cumulative1991_1995")])
cor(df[df$samplelife == 1, c("perf_life_exp_wpp_growth1995_2015", "life_exp_wpp_1995")])
```

## IMR regressions

```{r imr}
## base model
fit <- RunModel(imr_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + pc_rgdpe_avg_1995 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1991_1995)
car::vif(fit)
RunModel(imr_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + pc_rgdpe_avg_growth1995_2015 + v2x_polyarchy_cumulative1991_1995)
RunModel(imr_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + pc_rgdpe_avg_1995 + v2x_polyarchy_cumulative1991_1995)
cor(df[df$samplelife == 1, c("pc_rgdpe_avg_1995", "pc_rgdpe_avg_growth1995_2015")])
## Prediction model
RunModel(imr_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995)
RunModel(imr_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995, data = df[df$samplelife == 1, ])
```

## MYS regressions

```{r mys}
## Column 1: MYS base
fit <- RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1996_2015 + deaths_civilians_osv_rate_1995 + deaths_civilians_osv_rate_cumulative1996_2015)
df$samplemys <- ifelse(df$country %in% na.omit(get_all_vars(fit$call$formula, data = df, country = country))[, "country"], 1, 0)
## (checks)
RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1996_2015)
RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + deaths_civilians_osv_rate_cumulative1996_2015)
RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + deaths_civilians_osv_rate_1995)
RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1996_2015 + deaths_civilians_osv_rate_cumulative1996_2015)
cor(df[df$samplemys == 1, c("deaths_civilians_osv_rate_1995", "deaths_civilians_osv_rate_cumulative1996_2015")])
# auxilliary checks
# RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1996_2015 + deaths_civilians_int_rate_1995 + deaths_civilians_osv_rate_cumulative1996_2015)
# RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1996_2015 + conflict_internal_cumulative1989_1995 + deaths_civilians_osv_rate_cumulative1996_2015)
# RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1996_2015 + deaths_civilians_osv_rate_1995 + conflict_internal_cumulative1996_2015)
# RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1996_2015 + deaths_civilians_osv_rate_1995 + deaths_civilians_int_rate_cumulative1996_2015)
# RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1996_2015 + deaths_civilians_int_rate_1995 + deaths_civilians_osv_rate_cumulative1996_2015)
# RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1996_2015 + deaths_civilians_int_rate_1995 + conflict_internal_cumulative1996_2015)
# RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1996_2015 + conflict_internal_cumulative1989_1995 + conflict_internal_cumulative1996_2015)
# RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1996_2015 + conflict_internal_cumulative1989_1995 + deaths_civilians_int_rate_cumulative1996_2015)

## Column 2 MYS predict
RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1991_1995 + deaths_civilians_osv_rate_1995)
# auxilliary checks
# RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1991_1995 + deaths_civilians_int_rate_1995)
# RunModel(mys_ratio_hdr_growth1995_2015 ~ mys_ratio_hdr_1995 + asfr_adol_wpp_1995 + v2x_polyarchy_cumulative1991_1995 + conflict_internal_cumulative1989_1995)
```

## ASFR regressions

```{r asfr}
## column 3 ASFR base
RunModel(asfr_adol_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + v2x_partip_cumulative1996_2015)
## Column 4 ASFR predict
RunModel(asfr_adol_wpp_growth1995_2015 ~ imr_wpp_1995 + asfr_adol_wpp_1995 + v2x_partip_cumulative1991_1995)
```

## Conflict regressions

```{r conflict}
## column 1
RunModel(conflict_internal_cumulative1996_2015 ~ life_exp_wpp_1995 + conflict_internal_cumulative1989_1995)
## column 2
RunModel(conflict_internal_cumulative1996_2015 ~ imr_wpp_1995 + conflict_internal_cumulative1989_1995)
## column 3
RunModel(conflict_internal_cumulative1996_2015 ~ mys_ratio_hdr_1995 + conflict_internal_cumulative1989_1995)
## column 4
RunModel(deaths_civilians_int_rate_cumulative1996_2015 ~ mys_ratio_hdr_1995)
## column 5
RunModel(deaths_civilians_osv_rate_cumulative1996_2015 ~ mys_ratio_hdr_1995 + deaths_civilians_osv_rate_1995)
```

## Non-regression evidence of virtuous and vicious circles

```{r descriptives}
hist(df$life_exp_wpp_growth1995_2015) 
summary(df$life_exp_wpp_growth1995_2015)
summary(df$class_low_1995)
summary(df$class_low_1995[df$life_exp_wpp_growth1995_2015 < 2.3])
summary(df$class_upp_1995)
summary(df$class_upp_1995[df$life_exp_wpp_growth1995_2015 < 2.3])

hist(df$imr_wpp_growth1995_2015)
summary(df$imr_wpp_growth1995_2015)
summary(df$class_low_1995)
summary(df$class_low_1995[df$imr_wpp_growth1995_2015 < 2.71])
summary(df$class_upp_1995)
summary(df$class_upp_1995[df$imr_wpp_growth1995_2015 < 2.71])

hist(df$mys_ratio_hdr_growth1995_2015)
summary(df$mys_ratio_hdr_growth1995_2015)
summary(df$class_low_1995)
summary(df$class_low_1995[df$mys_ratio_hdr_growth1995_2015 < -0.00437])
summary(df$class_upp_1995)
summary(df$class_upp_1995[df$mys_ratio_hdr_growth1995_2015 < -0.00437])

hist(df$asfr_adol_wpp_growth1995_2015)
summary(df$asfr_adol_wpp_growth1995_2015)
summary(df$class_low_1995)
summary(df$class_low_1995[df$asfr_adol_wpp_growth1995_2015 < 2.7085])
summary(df$class_upp_1995)
summary(df$class_upp_1995[df$asfr_adol_wpp_growth1995_2015 < 2.7085])

hist(df$pc_rgdpe_avg_growth1995_2015)
summary(df$pc_rgdpe_avg_growth1995_2015) 
summary(df$class_low_1995)
summary(df$class_low_1995[df$pc_rgdpe_avg_growth1995_2015 < 144]) 
summary(df$class_upp_1995)
summary(df$class_upp_1995[df$pc_rgdpe_avg_growth1995_2015 < 144])

df$authority <- df$v2x_polyarchy_cumulative1996_2015 - df$v2x_polyarchy_cumulative1991_1995
hist(df$authority)
summary(df$authority)
```
