---
title: "Mapping trajectories"
params: 
  cache: true
  optimize: false
---

```{r setup, include = FALSE}
source("setup.R")
```
### {.tabset .tabset-fade .tabset-pills}

```{r data, results = "hide", rows.print = 15, cols.print = 12, cols.min.print = 12, message = FALSE}
IsTrue <- function(x) { !is.na(x) & x }
load("_data/LSCMWG_working_class.RData")
link <- "https://docs.google.com/spreadsheets/d/1KPUMNCixfyFU4KryzV0_5BYUHCUIyOq2heei9KdpSF8/edit?usp=sharing"
googlesheets4::gs4_deauth()
seq <- googlesheets4::read_sheet(link, sheet = "coding", na = "..")[, c("country", "sequence", "typology")]
save(seq, file = "_data/sequences.RData")
```

```{r class, results = 'hide', fig.width = 5, fig.height = 5, out.width = "25%", out.height = "25%", fig.show = "hold", eval = FALSE, echo = FALSE}
df <- unique(df[, c("country", "period", "health_class", "gender_class", "class", "class_vv")])
df$period <- str_sub(df$period, 7, 10)
df <- df[!is.na(df$class) & df$period != 2020, ]
# noquote(tapply(X = df$class_vv, INDEX = list(health = df$health_class, gender = df$gender_class), function(set) { paste(unique(set), collapse = "; ") }))
df_new <- pivot_wider(df[, c("country", "period", "class_vv")], names_from = period, values_from = class_vv)
df_new[, -1] <- lapply(df_new[, -1], function(col) {
  col[is.na(col)] <- ""
  return(col)
})
as.data.frame(df_new)
df_new <- pivot_wider(df[, c("country", "period", "class")], names_from = period, values_from = class)
df_new[, -1] <- lapply(df_new[, -1], function(col) {
  col[is.na(col)] <- ""
  return(col)
})
df <- df %>% arrange(country, period)
df <- df %>% group_by(country) %>% 
  mutate(lag_health_class = lag(health_class), lag_gender_class = lag(gender_class), lag_class = lag(class))
df <- df[!is.na(df$lag_class), ]
df <- df[IsTrue(df$lag_class != df$class), ]
list(as.data.frame(df_new[df_new$country %in% df_new$country[!df_new$country %in% unique(df$country)], ]))
lapply(unique(df$country), function(ctry) {
  ggplot(df[df$country == ctry, ], 
         aes(x = lag_gender_class, y = lag_health_class, xend = gender_class, yend = health_class)) + 
    geom_segment(arrow = arrow(angle = 15, type = "closed")) + 
    geom_point(aes(x = lag_gender_class[period == min(period)], 
                   y = lag_health_class[period == min(period)]), 
               shape = 22, size = 3, fill = "red") + 
    geom_point(aes(x = gender_class[period == max(period)], 
                   y = health_class[period == max(period)]), 
               shape = 23, size = 3, fill = "green") + 
    xlim(0.5, 5.5) + ylim(0.5, 5.5) + labs(x = "Gender", y = "Health") + theme_classic() + ggtitle(ctry)
})
```

```{r sequencing, results = 'hide', fig.width = 5, fig.height = 5, out.width = "25%", out.height = "25%", fig.show = "hold", warning = FALSE}
# vars <- names(df)
# vars <- vars[!str_detect(vars, "perf_")]
# lapply(c(variables$health, variables$gender), function(x) {
#   vars[str_detect(vars, x)]
# })
# vars[str_detect(vars, "class") ]
df <- df[df$year > 1965, ] %>% 
  arrange(country, year) %>% 
  group_by(country, period) %>% 
  mutate(latentmean_fariss_avg = mean(latentmean_fariss, na.rm = TRUE),
         v2caviol_avg = mean(v2caviol, na.rm = TRUE),
         v2clkill_avg = mean(v2clkill, na.rm = TRUE),
         v2cltort_avg = mean(v2cltort, na.rm = TRUE),
         hom_odcwho_rate_avg = mean(hom_odcwho_rate, na.rm = TRUE),
         deaths_all_int_rate_avg = mean(deaths_all_int_rate, na.rm = TRUE),
         deaths_all_nsc_rate_avg = mean(deaths_all_nsc_rate, na.rm = TRUE),
         deaths_civilians_osv_rate_avg = mean(deaths_civilians_osv_rate, na.rm = TRUE),
         deaths_civilians_int_rate_avg = mean(deaths_civilians_int_rate, na.rm = TRUE),
         deaths_civilians_nsc_rate_avg = mean(deaths_civilians_nsc_rate, na.rm = TRUE))
df <- df[, c("country", "year", "period", "health_class", "gender_class", "class", "class_vv", "class1990", "class_vv1990", "class1995", "class_vv1995", "life_exp_wpp_avg", "imr_wpp_avg", "mys_age_ratio_ihme_avg", "asfr_adol_wpp_avg", "latentmean_fariss_avg", "v2caviol_avg", "v2clkill_avg", "v2cltort_avg", "hom_odcwho_rate_avg", "deaths_all_int_rate_avg", "deaths_all_nsc_rate_avg", "deaths_civilians_osv_rate_avg", "deaths_civilians_int_rate_avg", "deaths_civilians_nsc_rate_avg")]
df$period <- as.integer(str_sub(df$period, 7, 10))
df <- df[df$period == df$year & df$period %in% seq(1970, 2015, 5), names(df) != "year"]
data.frame(class = table(df$period, is.na(df$class))[, 1],
           life = table(df$period, is.na(df$life_exp_wpp_avg))[, 1],
           imr = table(df$period, is.na(df$imr_wpp_avg))[, 1],
           asfr = table(df$period, is.na(df$asfr_adol_wpp_avg))[, 1],
           mys = table(df$period, is.na(df$mys_age_ratio_ihme_avg))[, 1])
class1975 <- df[IsTrue(df$period == 1975), c("country", "class", "health_class", "gender_class")]
class1975$class_vv <- NA
class1975$class_vv[class1975$health_class < 3 & class1975$gender_class < 3] <- "low"
class1975$class_vv[class1975$health_class > 3 & class1975$gender_class > 3] <- "upp"
class1975$class_vv[!(class1975$health_class < 3 & class1975$gender_class < 3) & !(class1975$health_class > 3 & class1975$gender_class > 3)] <- "mid"
class1975$class_vv[class1975$class_vv == "mid" & class1975$health_class > class1975$gender_class] <- "H>G"
class1975$class_vv[class1975$class_vv == "mid" & class1975$health_class < class1975$gender_class] <- "G>H"
names(class1975)[-1] <- paste(names(class1975)[-1], "1975", sep = "")
df <- merge(df, class1975, by = "country", all.x = TRUE)
df <- df[!is.na(df$country), ]
missing_countries <- c("Andorra", "Czechoslovakia", "Dominica", "East Germany", "Ethiopia", "Kosovo", "Liechtenstein", "Marshall Islands", "Monaco", "Nauru", "North Vietnam", "North Yemen", "Palau", "San Marino", "Saint Kitts & Nevis", "South Vietnam", "South Yemen", "Soviet Union", "Tuvalu", "West Germany", "Yugoslavia SFR", "South Sudan", "Serbia & Montenegro")
df <- df[!(df$country %in% missing_countries), ]

df$life_exp_wpp_avg <- as.numeric(scale(df$life_exp_wpp_avg))
df$imr_wpp_avg <- as.numeric(scale(df$imr_wpp_avg))
df$mys_age_ratio_ihme_avg <- as.numeric(scale(df$mys_age_ratio_ihme_avg))
df$asfr_adol_wpp_avg <- as.numeric(scale(df$asfr_adol_wpp_avg))
df$health <- rowMeans(df[, c("life_exp_wpp_avg", "imr_wpp_avg")], na.rm = FALSE)
df$gender <- rowMeans(df[, c("mys_age_ratio_ihme_avg", "asfr_adol_wpp_avg")], na.rm = FALSE)
df <- df %>% 
  arrange(country, period) %>% 
  group_by(country) %>% 
  mutate(lag_imr_wpp_avg = lag(imr_wpp_avg), 
         lag_asfr_adol_wpp_avg = lag(asfr_adol_wpp_avg),
         lag_life_exp_wpp_avg = lag(life_exp_wpp_avg),
         lag_mys_age_ratio_ihme_avg = lag(mys_age_ratio_ihme_avg),
         lag_health = lag(health),
         lag_gender = lag(gender))
mean_health <- mean(df$health, na.rm = TRUE)
range_health <- range(df$health, na.rm = TRUE)
mean_gender <- mean(df$gender, na.rm = TRUE)
range_gender <- range(df$gender, na.rm = TRUE)
range_both <- range(c(range_health, range_gender))
df$color <- ifelse((df$period %% 2) == 0, "black", "gray")
df$health_chg <- df$health - df$lag_health
df$gender_chg <- df$gender - df$lag_gender
# df$change[df$health_chg <= 0 & df$gender_chg <= 0] <- "worse"
# df$change[df$health_chg <= 0 & df$gender_chg > 0] <- "health worse"
# df$change[df$health_chg > 0 & df$gender_chg <= 0] <- "gender worse"
# df$change[df$health_chg > 0 & df$gender_chg > 0 & df$health_chg < df$gender_chg] <- "gender more"
# df$change[df$health_chg > 0 & df$gender_chg > 0 & df$health_chg > df$gender_chg] <- "health more"
df$distance <- sqrt((df$health_chg)^2 + (df$gender_chg)^2)
# df$slope <- (df$health - df$lag_health)/(df$gender - df$lag_gender)
df <- df %>% group_by(country) %>% mutate(total = sum(distance, na.rm = TRUE), first = min(period), last = max(period), periods = length(unique(period)))
first <- df[df$period == df$first, c("country", "first", "periods", "class_vv1975", "class_vv1995", "total", "health", "gender")]
names(first)[7:8] <- paste("first", names(first)[7:8], sep = "_")
last <- df[df$period == df$last, c("country", "health", "gender")]
names(last)[-1] <- paste("last", names(last)[-1], sep = "_")
new <- merge(first, last, by = "country")
new$distance <- sqrt((new$last_health - new$first_health)^2 + (new$last_gender - new$first_gender)^2)
new$dist_total <- new$distance / new$total
new$dist_period <- new$distance / new$periods
new$health_period = (new$last_health - new$first_health) / new$periods
new$gender_period = (new$last_gender - new$first_gender) / new$periods
new[, -c(1:5)] <- lapply(new[, -c(1:5)], round, 3)
new <- new[, !names(new) %in% c("last_health", "first_health", "last_gender", "first_gender")]
new <- merge(seq[, c("country", "typology")], new, by = "country", all = TRUE)
df <- merge(df, seq[, c("country", "typology")], by = "country", all = TRUE)
```

#### Countries
```{r countries, results = 'hide', fig.width = 5, fig.height = 5, out.width = "33%", out.height = "33%", fig.show = "hold", warning = FALSE}
lapply(unique(df$country), function(ctry) {
  ggplot(data = df[df$country == ctry & !is.na(df$lag_health) & !is.na(df$lag_gender), ], 
         mapping = aes(x = lag_gender, y = lag_health, xend = gender, yend = health) ) + 
    coord_fixed(ratio = 1) + 
    geom_vline(xintercept = mean_gender, color = "gray") + 
    geom_hline(yintercept = mean_health, color = "gray") + 
    geom_abline(intercept = 0, slope = 1, color = "gray") + 
    geom_segment(lineend = "round", mapping = aes (color = color)) + 
    scale_color_manual(values = c(black = "black", gray = "darkgray")) +
    geom_point(aes(x = lag_gender[period == min(period)], y = lag_health[period == min(period)]), 
               shape = 20, size = 0.75, color = "green", fill = "green") + 
    geom_point(aes(x = gender[period == max(period)], y = health[period == max(period)]), 
               shape = 20, size = 0.75, color = "red", fill = "red") + 
    xlim(range_both[1], range_both[2]) +
    ylim(range_both[1], range_both[2]) +
    labs(x = "Gender", y = "Health") + 
    theme_classic() + theme(legend.position = "none") + 
    ggtitle(paste(ctry, "\n", seq$typology[seq$country == ctry]))
})
```

#### By 1975 classification
```{r c1975, results = 'hide', fig.width = 5, fig.height = 5, out.width = "33%", out.height = "33%", fig.show = "hold", warning = FALSE}
lapply(c("low", "H>G", "G>H", "mid", "upp"), function(class) {
  ggplot(data = df[df$class_vv1975 == class & df$period >= 1975 & !is.na(df$lag_health) & !is.na(df$lag_gender), ], 
         mapping = aes(x = lag_gender, y = lag_health, xend = gender, yend = health, group = country, color = country)) + 
    coord_fixed(ratio = 1) + 
    geom_segment(lineend = "round", arrow = arrow(angle = 10, type = "open", length = unit(7, "points"))) + 
    # facet_wrap( ~ class_vv1975, ncol = 5) + 
    geom_vline(xintercept = mean_gender, color = "gray") + 
    geom_hline(yintercept = mean_health, color = "gray") + 
    labs(x = "Gender", y = "Health") + 
    xlim(range_both[1], range_both[2]) +
    ylim(range_both[1], range_both[2]) +
    theme_classic() + theme(legend.position = "none") + ggtitle(class)
})
```

#### By 1975 classification (from origin)
```{r new1975, results = 'hide', fig.width = 5, fig.height = 5, out.width = "33%", out.height = "33%", fig.show = "hold", warning = FALSE}
new1975 <- df[df$period >= 1975, ] %>%
  arrange(country, period) %>% 
  group_by(country) %>% 
  mutate(first = min(period),
         health_first = lag_health[period == first],
         gender_first = lag_gender[period == first])
# new1975 %>% select(country, period, first, health, lag_health, health_first, gender, lag_gender, gender_first) %>% print(n = 100) 
new1975 <- new1975 %>% mutate(health = health - health_first, 
                      lag_health = lag_health - health_first,
                      gender = gender - gender_first,
                      lag_gender = lag_gender - gender_first)
range_gender_new <- range(new1975$gender, na.rm = TRUE)
range_health_new <- range(new1975$health, na.rm = TRUE)
range_both_new <- range(c(range_gender_new, range_health_new))
lapply(c("low", "H>G", "G>H", "mid", "upp"), function(class) {
  ggplot(data = new1975[new1975$class_vv1975 == class & !is.na(new1975$lag_health) & !is.na(new1975$lag_gender), ], 
         mapping = aes(x = lag_gender, y = lag_health, xend = gender, yend = health, group = country, color = country)) + 
    coord_fixed(ratio = 1) + 
    geom_segment(lineend = "round", arrow = arrow(angle = 10, type = "open", length = unit(7, "points"))) + 
    geom_vline(xintercept = mean_gender, color = "gray") + 
    geom_hline(yintercept = mean_health, color = "gray") + 
    labs(x = "Gender", y = "Health") + 
    xlim(range_both_new[1], range_both_new[2]) +
    ylim(range_both_new[1], range_both_new[2]) +
    theme_classic() + theme(legend.position = "none") + ggtitle(class)
})
```

#### By 1995 classification
```{r c1995, results = 'hide', fig.width = 5, fig.height = 5, out.width = "33%", out.height = "33%", fig.show = "hold", warning = FALSE}
lapply(c("low", "H>G", "G>H", "mid", "upp"), function(class) {
  ggplot(data = df[df$class_vv1995 == class & df$period >= 1995 & !is.na(df$lag_health) & !is.na(df$lag_gender), ], 
         mapping = aes(x = lag_gender, y = lag_health, xend = gender, yend = health, group = country, color = country)) + 
    coord_fixed(ratio = 1) + 
    geom_segment(lineend = "round", arrow = arrow(angle = 10, type = "open", length = unit(7, "points"))) + 
    geom_vline(xintercept = mean_gender, color = "gray") + 
    geom_hline(yintercept = mean_health, color = "gray") + 
    labs(x = "Gender", y = "Health") + 
    xlim(range_both[1], range_both[2]) +
    ylim(range_both[1], range_both[2]) +
    theme_classic() + theme(legend.position = "none") + ggtitle(class)
})
```

#### By 1995 classification (from origin in 1995)
```{r new1995, results = 'hide', fig.width = 5, fig.height = 5, out.width = "33%", out.height = "33%", fig.show = "hold", warning = FALSE}
new1995 <- df %>%
  arrange(country, period) %>% 
  group_by(country) %>% 
  mutate(first = min(period))
new1995$first[new1995$first < 1995] <- 1995
new1995 <- new1995 %>% mutate(health_first = lag_health[period == first],
                              gender_first = lag_gender[period == first])
# new1995 %>% select(country, period, first, health, lag_health, health_first, gender, lag_gender, gender_first) %>% print(n = 100) 
new1995 <- new1995 %>% mutate(health = health - health_first, 
                      lag_health = lag_health - health_first,
                      gender = gender - gender_first,
                      lag_gender = lag_gender - gender_first)
range_gender_new <- range(new1995$gender, na.rm = TRUE)
range_health_new <- range(new1995$health, na.rm = TRUE)
range_both_new <- range(c(range_gender_new, range_health_new))
lapply(c("low", "H>G", "G>H", "mid", "upp"), function(class) {
  ggplot(data = new1995[new1995$class_vv1995 == class & !is.na(new1995$lag_health) & !is.na(new1995$lag_gender), ], 
         mapping = aes(x = lag_gender, y = lag_health, xend = gender, yend = health, group = country, color = country)) + 
    coord_fixed(ratio = 1) + 
    geom_segment(lineend = "round", arrow = arrow(angle = 10, type = "open", length = unit(7, "points"))) + 
    geom_vline(xintercept = mean_gender, color = "gray") + 
    geom_hline(yintercept = mean_health, color = "gray") + 
    labs(x = "Gender", y = "Health") + 
    xlim(range_both_new[1], range_both_new[2]) +
    ylim(range_both_new[1], range_both_new[2]) +
    theme_classic() + theme(legend.position = "none") + ggtitle(class)
})
```

#### Typology
```{r typology, results = 'hide', fig.width = 5, fig.height = 5, out.width = "33%", out.height = "33%", fig.show = "hold", warning = FALSE}
lapply(sort(unique(df$typology)), function(sequ) {
  ggplot(data = df[df$typology == sequ & df$period >= 1975 & !is.na(df$lag_health) & !is.na(df$lag_gender), ], 
         mapping = aes(x = lag_gender, y = lag_health, xend = gender, yend = health, group = country, color = country)) + 
    coord_fixed(ratio = 1) + 
    geom_segment(lineend = "round", arrow = arrow(angle = 10, type = "open", length = unit(7, "points"))) + 
    # facet_wrap( ~ class_vv1975, ncol = 5) + 
    geom_vline(xintercept = mean_gender, color = "gray") + 
    geom_hline(yintercept = mean_health, color = "gray") + 
    labs(x = "Gender", y = "Health") + 
    xlim(range_both[1], range_both[2]) +
    ylim(range_both[1], range_both[2]) +
    theme_classic() + theme(legend.position = "none") + 
    ggtitle(paste(sequ, " (", table(seq$typology)[sequ], ")", sep = ""))
})
```

#### Summary data
```{r table, rows.print = 15, cols.print = 10, cols.min.print = 10}
new[, !names(new) %in% c("periods", "distance", "total")]
summary(new[, c("periods", "total", "distance", "dist_total", "dist_period", "health_period", "gender_period")])
```

#### Health & gender change
```{r bivariate, rows.print = 15, cols.print = 12, cols.min.print = 12, fig.width = 10, fig.height = 10, out.width = "67%", out.height = "67%", message = FALSE}
round(addmargins((table(new[, c("typology", "class_vv1975")]))), 3)
round(do.call(rbind, tapply(new$dist_period, new$typology, summary))[, c("Min.", "Mean", "Max.")], 3)
round(do.call(rbind, tapply(new$dist_total, new$typology, summary))[, c("Min.", "Mean", "Max.")], 3)
round(do.call(rbind, tapply(new$gender_period, new$typology, summary))[, c("Min.", "Mean", "Max.")], 3)
round(do.call(rbind, tapply(new$health_period, new$typology, summary))[, c("Min.", "Mean", "Max.")], 3)
ggplot(data = new, mapping = aes(x = gender_period, y = health_period)) + 
  facet_wrap(~typology) + 
  coord_fixed(ratio = 1)+
  theme_classic() + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  # geom_abline(intercept = 0, slope = 1) +
  xlim(min(0, new$gender_period, new$health_period), max(new$gender_period, new$health_period)) + 
  ylim(min(0, new$gender_period, new$health_period), max(new$gender_period, new$health_period)) + 
  theme(legend.position = "bottom") + 
  guides(color = guide_legend(ncol = 1))
```

```{r new, rows.print = 15, cols.print = 12, cols.min.print = 12, fig.width = 5, fig.height = 5, out.width = "50%", out.height = "50%", message = FALSE, eval = FALSE, echo = FALSE}
ggplot(data = new, mapping = aes(x = gender_period, y = health_period)) + 
  coord_fixed(ratio = 1)+
  theme_classic() + 
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  geom_smooth(method = "lm") + 
  xlim(min(0, new$gender_period, new$health_period), max(new$gender_period, new$health_period)) + 
  ylim(min(0, new$gender_period, new$health_period), max(new$gender_period, new$health_period)) + 
  theme(legend.position = "bottom") + 
  guides(color = guide_legend(ncol = 1))
```

#### Violence {.tabset .tabset-fade .tabset-pills}

##### Death rates
```{r violence_rates, fig.width = 10, fig.height = 10, out.width = "67%", out.height = "67%", warning = FALSE}
temp <- df %>% 
  arrange(country, period) %>% 
  group_by(period) %>% 
  select(country, period, typology, deaths_all_int_rate_avg, deaths_all_nsc_rate_avg, hom_odcwho_rate_avg) %>% 
  pivot_longer(-c(country, period, typology), names_to = "variable", values_to = "value")
ggplot(data = temp) + 
  stat_summary(mapping = aes(x = period, y = value, color = variable), fun = "mean", geom = "line") + 
  facet_wrap(~typology) + theme_classic() + theme(legend.position = "bottom")
```

##### V-Dem variables
```{r violence_vdem, fig.width = 10, fig.height = 10, out.width = "67%", out.height = "67%", warning = FALSE}
temp <- df %>% 
  arrange(country, period) %>% 
  group_by(period) %>% 
  select(country, period, typology, v2caviol_avg, v2clkill_avg, v2cltort_avg) %>% 
  pivot_longer(-c(country, period, typology), names_to = "variable", values_to = "value")
ggplot(data = temp) + 
  stat_summary(mapping = aes(x = period, y = value, color = variable), fun = "mean", geom = "line") + 
  facet_wrap(~typology) + theme_classic() + theme(legend.position = "bottom")
```

##### Latent physical integrity
```{r violence_lpi, fig.width = 10, fig.height = 10, out.width = "67%", out.height = "67%", warning = FALSE}
ggplot(data = df) + 
  stat_summary(mapping = aes(x = period, y = latentmean_fariss_avg), fun = "mean", geom = "line") +
  facet_wrap(~typology) + theme_classic()
```
